// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.19.4
// source: order.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EcommerceService_AddOrders_FullMethodName     = "/ecommerce.EcommerceService/AddOrders"
	EcommerceService_UpdateOrders_FullMethodName  = "/ecommerce.EcommerceService/UpdateOrders"
	EcommerceService_DelOrders_FullMethodName     = "/ecommerce.EcommerceService/DelOrders"
	EcommerceService_GetOrdersById_FullMethodName = "/ecommerce.EcommerceService/GetOrdersById"
	EcommerceService_SearchOrders_FullMethodName  = "/ecommerce.EcommerceService/SearchOrders"
)

// EcommerceServiceClient is the client API for EcommerceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EcommerceServiceClient interface {
	// -----------------------orders-----------------------
	AddOrders(ctx context.Context, in *AddOrdersReq, opts ...grpc.CallOption) (*AddOrdersResp, error)
	UpdateOrders(ctx context.Context, in *UpdateOrdersReq, opts ...grpc.CallOption) (*UpdateOrdersResp, error)
	DelOrders(ctx context.Context, in *DelOrdersReq, opts ...grpc.CallOption) (*DelOrdersResp, error)
	GetOrdersById(ctx context.Context, in *GetOrdersByIdReq, opts ...grpc.CallOption) (*GetOrdersByIdResp, error)
	SearchOrders(ctx context.Context, in *SearchOrdersReq, opts ...grpc.CallOption) (*SearchOrdersResp, error)
}

type ecommerceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEcommerceServiceClient(cc grpc.ClientConnInterface) EcommerceServiceClient {
	return &ecommerceServiceClient{cc}
}

func (c *ecommerceServiceClient) AddOrders(ctx context.Context, in *AddOrdersReq, opts ...grpc.CallOption) (*AddOrdersResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddOrdersResp)
	err := c.cc.Invoke(ctx, EcommerceService_AddOrders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ecommerceServiceClient) UpdateOrders(ctx context.Context, in *UpdateOrdersReq, opts ...grpc.CallOption) (*UpdateOrdersResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateOrdersResp)
	err := c.cc.Invoke(ctx, EcommerceService_UpdateOrders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ecommerceServiceClient) DelOrders(ctx context.Context, in *DelOrdersReq, opts ...grpc.CallOption) (*DelOrdersResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DelOrdersResp)
	err := c.cc.Invoke(ctx, EcommerceService_DelOrders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ecommerceServiceClient) GetOrdersById(ctx context.Context, in *GetOrdersByIdReq, opts ...grpc.CallOption) (*GetOrdersByIdResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOrdersByIdResp)
	err := c.cc.Invoke(ctx, EcommerceService_GetOrdersById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ecommerceServiceClient) SearchOrders(ctx context.Context, in *SearchOrdersReq, opts ...grpc.CallOption) (*SearchOrdersResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchOrdersResp)
	err := c.cc.Invoke(ctx, EcommerceService_SearchOrders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EcommerceServiceServer is the server API for EcommerceService service.
// All implementations must embed UnimplementedEcommerceServiceServer
// for forward compatibility.
type EcommerceServiceServer interface {
	// -----------------------orders-----------------------
	AddOrders(context.Context, *AddOrdersReq) (*AddOrdersResp, error)
	UpdateOrders(context.Context, *UpdateOrdersReq) (*UpdateOrdersResp, error)
	DelOrders(context.Context, *DelOrdersReq) (*DelOrdersResp, error)
	GetOrdersById(context.Context, *GetOrdersByIdReq) (*GetOrdersByIdResp, error)
	SearchOrders(context.Context, *SearchOrdersReq) (*SearchOrdersResp, error)
	mustEmbedUnimplementedEcommerceServiceServer()
}

// UnimplementedEcommerceServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEcommerceServiceServer struct{}

func (UnimplementedEcommerceServiceServer) AddOrders(context.Context, *AddOrdersReq) (*AddOrdersResp, error) {
	return nil, status.Error(codes.Unimplemented, "method AddOrders not implemented")
}
func (UnimplementedEcommerceServiceServer) UpdateOrders(context.Context, *UpdateOrdersReq) (*UpdateOrdersResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateOrders not implemented")
}
func (UnimplementedEcommerceServiceServer) DelOrders(context.Context, *DelOrdersReq) (*DelOrdersResp, error) {
	return nil, status.Error(codes.Unimplemented, "method DelOrders not implemented")
}
func (UnimplementedEcommerceServiceServer) GetOrdersById(context.Context, *GetOrdersByIdReq) (*GetOrdersByIdResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOrdersById not implemented")
}
func (UnimplementedEcommerceServiceServer) SearchOrders(context.Context, *SearchOrdersReq) (*SearchOrdersResp, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchOrders not implemented")
}
func (UnimplementedEcommerceServiceServer) mustEmbedUnimplementedEcommerceServiceServer() {}
func (UnimplementedEcommerceServiceServer) testEmbeddedByValue()                          {}

// UnsafeEcommerceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EcommerceServiceServer will
// result in compilation errors.
type UnsafeEcommerceServiceServer interface {
	mustEmbedUnimplementedEcommerceServiceServer()
}

func RegisterEcommerceServiceServer(s grpc.ServiceRegistrar, srv EcommerceServiceServer) {
	// If the following call panics, it indicates UnimplementedEcommerceServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EcommerceService_ServiceDesc, srv)
}

func _EcommerceService_AddOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddOrdersReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EcommerceServiceServer).AddOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EcommerceService_AddOrders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EcommerceServiceServer).AddOrders(ctx, req.(*AddOrdersReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EcommerceService_UpdateOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateOrdersReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EcommerceServiceServer).UpdateOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EcommerceService_UpdateOrders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EcommerceServiceServer).UpdateOrders(ctx, req.(*UpdateOrdersReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EcommerceService_DelOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelOrdersReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EcommerceServiceServer).DelOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EcommerceService_DelOrders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EcommerceServiceServer).DelOrders(ctx, req.(*DelOrdersReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EcommerceService_GetOrdersById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrdersByIdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EcommerceServiceServer).GetOrdersById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EcommerceService_GetOrdersById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EcommerceServiceServer).GetOrdersById(ctx, req.(*GetOrdersByIdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _EcommerceService_SearchOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchOrdersReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EcommerceServiceServer).SearchOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EcommerceService_SearchOrders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EcommerceServiceServer).SearchOrders(ctx, req.(*SearchOrdersReq))
	}
	return interceptor(ctx, in, info, handler)
}

// EcommerceService_ServiceDesc is the grpc.ServiceDesc for EcommerceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EcommerceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ecommerce.EcommerceService",
	HandlerType: (*EcommerceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddOrders",
			Handler:    _EcommerceService_AddOrders_Handler,
		},
		{
			MethodName: "UpdateOrders",
			Handler:    _EcommerceService_UpdateOrders_Handler,
		},
		{
			MethodName: "DelOrders",
			Handler:    _EcommerceService_DelOrders_Handler,
		},
		{
			MethodName: "GetOrdersById",
			Handler:    _EcommerceService_GetOrdersById_Handler,
		},
		{
			MethodName: "SearchOrders",
			Handler:    _EcommerceService_SearchOrders_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "order.proto",
}
