// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.4
// source: order.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// --------------------------------orders--------------------------------
type Orders struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`     //订单名称
	Num           int64                  `protobuf:"varint,2,opt,name=num,proto3" json:"num,omitempty"`      //订单数量
	Price         float64                `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"` //订单金额
	Id            int64                  `protobuf:"varint,4,opt,name=id,proto3" json:"id,omitempty"`        //id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Orders) Reset() {
	*x = Orders{}
	mi := &file_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Orders) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Orders) ProtoMessage() {}

func (x *Orders) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Orders.ProtoReflect.Descriptor instead.
func (*Orders) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{0}
}

func (x *Orders) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Orders) GetNum() int64 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *Orders) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Orders) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type AddOrdersReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`     //订单名称
	Num           int64                  `protobuf:"varint,2,opt,name=num,proto3" json:"num,omitempty"`      //订单数量
	Price         float64                `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"` //订单金额
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddOrdersReq) Reset() {
	*x = AddOrdersReq{}
	mi := &file_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddOrdersReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddOrdersReq) ProtoMessage() {}

func (x *AddOrdersReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddOrdersReq.ProtoReflect.Descriptor instead.
func (*AddOrdersReq) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{1}
}

func (x *AddOrdersReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddOrdersReq) GetNum() int64 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *AddOrdersReq) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type AddOrdersResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddOrdersResp) Reset() {
	*x = AddOrdersResp{}
	mi := &file_order_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddOrdersResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddOrdersResp) ProtoMessage() {}

func (x *AddOrdersResp) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddOrdersResp.ProtoReflect.Descriptor instead.
func (*AddOrdersResp) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{2}
}

func (x *AddOrdersResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UpdateOrdersReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Price         float64                `protobuf:"fixed64,1,opt,name=price,proto3" json:"price,omitempty"` //订单金额
	Id            int64                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`        //id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOrdersReq) Reset() {
	*x = UpdateOrdersReq{}
	mi := &file_order_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOrdersReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrdersReq) ProtoMessage() {}

func (x *UpdateOrdersReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrdersReq.ProtoReflect.Descriptor instead.
func (*UpdateOrdersReq) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateOrdersReq) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *UpdateOrdersReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UpdateOrdersResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOrdersResp) Reset() {
	*x = UpdateOrdersResp{}
	mi := &file_order_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOrdersResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrdersResp) ProtoMessage() {}

func (x *UpdateOrdersResp) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrdersResp.ProtoReflect.Descriptor instead.
func (*UpdateOrdersResp) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateOrdersResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DelOrdersReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` //id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelOrdersReq) Reset() {
	*x = DelOrdersReq{}
	mi := &file_order_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelOrdersReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelOrdersReq) ProtoMessage() {}

func (x *DelOrdersReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelOrdersReq.ProtoReflect.Descriptor instead.
func (*DelOrdersReq) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{5}
}

func (x *DelOrdersReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DelOrdersResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelOrdersResp) Reset() {
	*x = DelOrdersResp{}
	mi := &file_order_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelOrdersResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelOrdersResp) ProtoMessage() {}

func (x *DelOrdersResp) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelOrdersResp.ProtoReflect.Descriptor instead.
func (*DelOrdersResp) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{6}
}

func (x *DelOrdersResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetOrdersByIdReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` //id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrdersByIdReq) Reset() {
	*x = GetOrdersByIdReq{}
	mi := &file_order_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrdersByIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrdersByIdReq) ProtoMessage() {}

func (x *GetOrdersByIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrdersByIdReq.ProtoReflect.Descriptor instead.
func (*GetOrdersByIdReq) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{7}
}

func (x *GetOrdersByIdReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetOrdersByIdResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        *Orders                `protobuf:"bytes,1,opt,name=orders,proto3" json:"orders,omitempty"` //orders
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrdersByIdResp) Reset() {
	*x = GetOrdersByIdResp{}
	mi := &file_order_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrdersByIdResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrdersByIdResp) ProtoMessage() {}

func (x *GetOrdersByIdResp) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrdersByIdResp.ProtoReflect.Descriptor instead.
func (*GetOrdersByIdResp) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{8}
}

func (x *GetOrdersByIdResp) GetOrders() *Orders {
	if x != nil {
		return x.Orders
	}
	return nil
}

type SearchOrdersReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int64                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"` //page
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Id            int64                  `protobuf:"varint,4,opt,name=id,proto3" json:"id,omitempty"`
	MinPrice      float32                `protobuf:"fixed32,5,opt,name=min_price,json=minPrice,proto3" json:"min_price,omitempty"`
	MaxPrice      float32                `protobuf:"fixed32,6,opt,name=max_price,json=maxPrice,proto3" json:"max_price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchOrdersReq) Reset() {
	*x = SearchOrdersReq{}
	mi := &file_order_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchOrdersReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchOrdersReq) ProtoMessage() {}

func (x *SearchOrdersReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchOrdersReq.ProtoReflect.Descriptor instead.
func (*SearchOrdersReq) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{9}
}

func (x *SearchOrdersReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchOrdersReq) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *SearchOrdersReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SearchOrdersReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SearchOrdersReq) GetMinPrice() float32 {
	if x != nil {
		return x.MinPrice
	}
	return 0
}

func (x *SearchOrdersReq) GetMaxPrice() float32 {
	if x != nil {
		return x.MaxPrice
	}
	return 0
}

type SearchOrdersResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*Orders              `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"` //orders
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchOrdersResp) Reset() {
	*x = SearchOrdersResp{}
	mi := &file_order_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchOrdersResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchOrdersResp) ProtoMessage() {}

func (x *SearchOrdersResp) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchOrdersResp.ProtoReflect.Descriptor instead.
func (*SearchOrdersResp) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{10}
}

func (x *SearchOrdersResp) GetOrders() []*Orders {
	if x != nil {
		return x.Orders
	}
	return nil
}

var File_order_proto protoreflect.FileDescriptor

const file_order_proto_rawDesc = "" +
	"\n" +
	"\vorder.proto\x12\tecommerce\"T\n" +
	"\x06Orders\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03num\x18\x02 \x01(\x03R\x03num\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x01R\x05price\x12\x0e\n" +
	"\x02id\x18\x04 \x01(\x03R\x02id\"J\n" +
	"\fAddOrdersReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03num\x18\x02 \x01(\x03R\x03num\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x01R\x05price\")\n" +
	"\rAddOrdersResp\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"7\n" +
	"\x0fUpdateOrdersReq\x12\x14\n" +
	"\x05price\x18\x01 \x01(\x01R\x05price\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x03R\x02id\",\n" +
	"\x10UpdateOrdersResp\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x1e\n" +
	"\fDelOrdersReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\")\n" +
	"\rDelOrdersResp\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\"\n" +
	"\x10GetOrdersByIdReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\">\n" +
	"\x11GetOrdersByIdResp\x12)\n" +
	"\x06orders\x18\x01 \x01(\v2\x11.ecommerce.OrdersR\x06orders\"\x97\x01\n" +
	"\x0fSearchOrdersReq\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x03R\x04page\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x0e\n" +
	"\x02id\x18\x04 \x01(\x03R\x02id\x12\x1b\n" +
	"\tmin_price\x18\x05 \x01(\x02R\bminPrice\x12\x1b\n" +
	"\tmax_price\x18\x06 \x01(\x02R\bmaxPrice\"=\n" +
	"\x10SearchOrdersResp\x12)\n" +
	"\x06orders\x18\x01 \x03(\v2\x11.ecommerce.OrdersR\x06orders2\xf0\x02\n" +
	"\x10EcommerceService\x12>\n" +
	"\tAddOrders\x12\x17.ecommerce.AddOrdersReq\x1a\x18.ecommerce.AddOrdersResp\x12G\n" +
	"\fUpdateOrders\x12\x1a.ecommerce.UpdateOrdersReq\x1a\x1b.ecommerce.UpdateOrdersResp\x12>\n" +
	"\tDelOrders\x12\x17.ecommerce.DelOrdersReq\x1a\x18.ecommerce.DelOrdersResp\x12J\n" +
	"\rGetOrdersById\x12\x1b.ecommerce.GetOrdersByIdReq\x1a\x1c.ecommerce.GetOrdersByIdResp\x12G\n" +
	"\fSearchOrders\x12\x1a.ecommerce.SearchOrdersReq\x1a\x1b.ecommerce.SearchOrdersRespB\x04Z\x02./b\x06proto3"

var (
	file_order_proto_rawDescOnce sync.Once
	file_order_proto_rawDescData []byte
)

func file_order_proto_rawDescGZIP() []byte {
	file_order_proto_rawDescOnce.Do(func() {
		file_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_order_proto_rawDesc), len(file_order_proto_rawDesc)))
	})
	return file_order_proto_rawDescData
}

var file_order_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_order_proto_goTypes = []any{
	(*Orders)(nil),            // 0: ecommerce.Orders
	(*AddOrdersReq)(nil),      // 1: ecommerce.AddOrdersReq
	(*AddOrdersResp)(nil),     // 2: ecommerce.AddOrdersResp
	(*UpdateOrdersReq)(nil),   // 3: ecommerce.UpdateOrdersReq
	(*UpdateOrdersResp)(nil),  // 4: ecommerce.UpdateOrdersResp
	(*DelOrdersReq)(nil),      // 5: ecommerce.DelOrdersReq
	(*DelOrdersResp)(nil),     // 6: ecommerce.DelOrdersResp
	(*GetOrdersByIdReq)(nil),  // 7: ecommerce.GetOrdersByIdReq
	(*GetOrdersByIdResp)(nil), // 8: ecommerce.GetOrdersByIdResp
	(*SearchOrdersReq)(nil),   // 9: ecommerce.SearchOrdersReq
	(*SearchOrdersResp)(nil),  // 10: ecommerce.SearchOrdersResp
}
var file_order_proto_depIdxs = []int32{
	0,  // 0: ecommerce.GetOrdersByIdResp.orders:type_name -> ecommerce.Orders
	0,  // 1: ecommerce.SearchOrdersResp.orders:type_name -> ecommerce.Orders
	1,  // 2: ecommerce.EcommerceService.AddOrders:input_type -> ecommerce.AddOrdersReq
	3,  // 3: ecommerce.EcommerceService.UpdateOrders:input_type -> ecommerce.UpdateOrdersReq
	5,  // 4: ecommerce.EcommerceService.DelOrders:input_type -> ecommerce.DelOrdersReq
	7,  // 5: ecommerce.EcommerceService.GetOrdersById:input_type -> ecommerce.GetOrdersByIdReq
	9,  // 6: ecommerce.EcommerceService.SearchOrders:input_type -> ecommerce.SearchOrdersReq
	2,  // 7: ecommerce.EcommerceService.AddOrders:output_type -> ecommerce.AddOrdersResp
	4,  // 8: ecommerce.EcommerceService.UpdateOrders:output_type -> ecommerce.UpdateOrdersResp
	6,  // 9: ecommerce.EcommerceService.DelOrders:output_type -> ecommerce.DelOrdersResp
	8,  // 10: ecommerce.EcommerceService.GetOrdersById:output_type -> ecommerce.GetOrdersByIdResp
	10, // 11: ecommerce.EcommerceService.SearchOrders:output_type -> ecommerce.SearchOrdersResp
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_order_proto_init() }
func file_order_proto_init() {
	if File_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_order_proto_rawDesc), len(file_order_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_order_proto_goTypes,
		DependencyIndexes: file_order_proto_depIdxs,
		MessageInfos:      file_order_proto_msgTypes,
	}.Build()
	File_order_proto = out.File
	file_order_proto_goTypes = nil
	file_order_proto_depIdxs = nil
}
